name: Run .NET Tests

on:
  push:
    branches:
      - develop/harun

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.x  # Change to your desired version

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
