name: Run Tests

on:
  push:
    branches:
      - develop/harun

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.x  # Change to your desired version

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --configuration Release --no-restore

