name: Main Workflow

on:
  push:
    branches:
      - develop/harun

jobs:
  run_actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Webhooks Action
        uses: ./webhooks/.github/actions/action.yml

