name: Run Tests

on:
  push:
    branches:
      - develop/harun

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      - name: Build and Test
        run: |
          dotnet clean
          dotnet restore
          dotnet test 
        # env:
        #   Client_Id: ${{ secrets.CLIENT_ID }}
        #   Client_Secret: ${{ secrets.CLIENT_SECRET }}

      # - name: Build
      #   run: dotnet build

      # - name: Test DataManagement
      #   run: |
      #     cd datamanagement/test
      #     dotnet test --configuration Release

      # - name: Test OSS
      #   run: |
      #     cd oss/test
      #     dotnet test --configuration Release

      # - name: Test Webhooks
      #   run: |
      #     cd webhooks/test
      #     dotnet test --configuration Release

      # - name: Test ModelDerivative
      #   run: |
      #     cd modelderivative/test
      #     dotnet test --configuration Release
